export const FETCHING_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FETCH_MORE_DATA_SUCCESS = 'FETCH_MORE_DATA_SUCCESS';
export const FETCH_MORE_DATA_ERROR = 'FETCH_MORE_DATA_ERROR';
